name: japangateway
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/gateway.png
    - assets/images/red-gate-icon.png
    - assets/images/mouse-icon.png
    - assets/images/tmp/mission-photo-placeholder-1.png
    - assets/images/tmp/mission-photo-placeholder-2.png
    - assets/images/tmp/support-photo-placeholder.png
    - assets/images/tmp/placeholder-button.png
    - assets/images/tmp/why-photo-placeholder.png
    
  fonts:
    - family: Spectral
      fonts:
        - asset: assets/fonts/Spectral/Spectral-Regular.ttf
          weight: 400
        - asset: assets/fonts/Spectral/Spectral-Bold.ttf
          weight: 700
    - family: M_PLUS_1
      fonts:
        - asset: assets/fonts/M_PLUS_1/MPLUS1-Light.ttf
          weight: 300
        - asset: assets/fonts/M_PLUS_1/MPLUS1-Regular.ttf
          weight: 400
        - asset: assets/fonts/M_PLUS_1/MPLUS1-Medium.ttf
          weight: 500
        - asset: assets/fonts/M_PLUS_1/MPLUS1-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/M_PLUS_1/MPLUS1-Bold.ttf
          weight: 700
        - asset: assets/fonts/M_PLUS_1/MPLUS1-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/M_PLUS_1/MPLUS1-Black.ttf
          weight: 900
    - family: Lato
      fonts: 
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
